### ISSUE TITLE
Consider Documenting Configuration

### ISSUE THREAD

**Issue by Kurt-von-Laven** [shiranr/linkcheck#1]
I may have misunderstood the way this tool works, but at face value my impression is that I would need to dive into the source code in order to understand what configuration options are available.

**Comment by shiranr** [comment]
Hi @Kurt-von-Laven,
Thank you for your feedback, really appreciated.
This is the first release of the plugin, I will improve the documentation and the option to customize the plugin.

**Comment by Kurt-von-Laven** [comment]
Thank you for creating it!

**Comment by Kurt-von-Laven** [comment]
Personally, I feel like you did this one, and it can be closed, but did you have more work planned here?

**Comment by shiranr** [comment]
On this one I don't so I will close it :)
But I do have an expansion to this plugin coming soon.
